baseURL = "https://wbira.github.io/"
languageCode = "en-us"
title = "Vi Valdi"
theme = "noteworthy"

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "4 seasons of coding"
	mainSections = ["post"]

	github = "https://github.com/wbira"
	email = "mailto:waldek.bira@gmail.com"
	linkedin = "https://www.linkedin.com/in/waldemar-bira-72328179/"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 2


[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 3
